package com.github.zipcodewilmington;

import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import java.util.Scanner;

public class Wordguess {
    //Andy Zheng


    public static List<String> words = new ArrayList<>(); //putting the list in the Word guess class so other methods can get it
    public static void main(String[] args){
        //create a list with words
        words.add("apple");
        words.add("zipcode");
        words.add("saveme");

        startGame();

    }
    public static int randomNumGen(){
        Random random = new Random();   //random obj to use random class
        int randomNumber = random.nextInt(3); //gen random num form 0 to 3 not including 3, i think
        return randomNumber;
    }

    public static String getWordbyIndex(int randomNumGen){  //taking in random num generated by randomNumGen to call the index of the list

        return words.get(randomNumGen);
    }

    public static int getLengthofWord(String getWordbyIndex){ //taking in the word from getWordbyIndex method and return the length
        //System.out.println(getWordbyIndex); // to see what word the length is referring to
        return getWordbyIndex.length();
    }


    public static void startGame(){
        String wordToGuess = getWordbyIndex(randomNumGen());
        int maxNumOfguesses = wordToGuess.length();
        int userGuesses = 0;
        char[] wordArray = wordToGuess.toCharArray();
        char[] userGuess = new char[wordToGuess.length()];

        //

        Scanner scanner = new Scanner(System.in);
        while(userGuesses < maxNumOfguesses){
            System.out.println("Type guess to guess the word or type a letter: ");
            String guess = scanner.nextLine();

            if(guess.equals("guess")){
                if(guess.equals(wordToGuess)){
                    System.out.println("You have guessed correctly");
                    break;
                }else{
                    System.out.println("Incorrect guess");
                    userGuesses++;
                }
            }

        }
        System.out.println("Game Over");




    }
}
