package com.github.zipcodewilmington;

import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import java.util.Scanner;

public class Wordguess {
    //Andy Zheng


    public static List<String> words = new ArrayList<>(); //putting the list in the Word guess class so other methods can get it
    public static void main(String[] args){
        //create a list with words
        words.add("apple");
        words.add("zipcode");
        words.add("saveme");

        startGame();

    }
    public static int randomNumGen(){
        Random random = new Random();   //random obj to use random class
        int randomNumber = random.nextInt(3); //gen random num form 0 to 3 not including 3, i think
        return randomNumber;
    }

    public static String getWordbyIndex(int randomNumGen){  //taking in random num generated by randomNumGen to call the index of the list

        return words.get(randomNumGen);
    }

    public static int getLengthofWord(String getWordbyIndex){ //taking in the word from getWordbyIndex method and return the length
        //System.out.println(getWordbyIndex); // to see what word the length is referring to
        return getWordbyIndex.length();
    }


    public static void startGame(){
        String wordToGuess = getWordbyIndex(randomNumGen());
        int maxNumOfguesses = wordToGuess.length();
        int userGuesses = 0;
        char[] wordArray = wordToGuess.toCharArray();
        char[] userGuess = new char[wordToGuess.length()]; // Array to keep track of correct guesses

        // Initialize userGuess array with underscores to represent unguessed letters
        for(int i = 0; i < userGuess.length; i++) {
            userGuess[i] = '_';
        }

        Scanner scanner = new Scanner(System.in);
        while(userGuesses < maxNumOfguesses){
            System.out.println("Type 'guess' to guess the word or type a letter: ");
            String input = scanner.nextLine();

            // Check if the user wants to guess the whole word
            if(input.equalsIgnoreCase("guess")){
                System.out.println("Enter your guess for the word: ");
                String wordGuess = scanner.nextLine();
                if(wordGuess.equalsIgnoreCase(wordToGuess)) {
                    System.out.println("You have guessed correctly!");
                    return; // Exit the function if the word is guessed correctly
                }else{
                    System.out.println("Incorrect guess.");
                    userGuesses++;
                }
            } else if (input.length() == 1) { // User is guessing one letter
                char charGuess = input.charAt(0);
                boolean correctGuess = false;

                // Check each letter of the word
                for(int i = 0; i < wordArray.length; i++) {
                    if(wordArray[i] == charGuess) {
                        userGuess[i] = charGuess; // Reveal the letter in userGuess array
                        correctGuess = true;
                    }
                }

                if(correctGuess) {
                    System.out.println("Correct! " + new String(userGuess));
                    // Check if all letters have been guessed
                    if(new String(userGuess).equalsIgnoreCase(wordToGuess)) {
                        System.out.println("All letters guessed!");
                        break;
                    }
                } else {
                    System.out.println("Incorrect guess, try again.");
                    userGuesses++;
                }
            } else {
                System.out.println("Invalid input, please try again.");
            }
        }
        System.out.println("Game Over. The word was: " + wordToGuess);
    }
}
